services:
  - type: web
    name: stroke-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    workingDir: backend
